documentation.json
src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.ts
src/app/components/shared/video-player/video-player.component.html
src/app/components/shared/video-player/video-player.component.scss
src/app/components/shared/video-player/video-player.component.spec.ts
src/app/components/shared/video-player/video-player.component.ts
src/stories/video-player.component.stories.ts

Creating video player component
**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

[HCPS] - video player

---

src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.ts
src/app/components/shared/link/link.component.html
src/app/components/shared/link/link.component.scss
src/app/components/shared/link/link.component.spec.ts
src/app/components/shared/link/link.component.ts
src/stories/link.component.stories.ts
src/styles/mixins.scss
src/styles/variables.scss

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

[HCSP] - link component

---

documentation.json
src/app/app.config.ts
src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.ts
src/app/components/shared/accordion/accordion.component.html
src/app/components/shared/accordion/accordion.component.scss
src/app/components/shared/accordion/accordion.component.spec.ts
src/app/components/shared/accordion/accordion.component.ts
src/stories/accordion.stories.ts

----------------
**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

[HCPS] - accordion component

---

src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.ts
src/app/components/shared/article-feedback/article-feedback.component.scss
src/app/components/shared/article-index/article-index.component.scss
src/app/components/shared/breadcrum/breadcrumb.component.scss
src/app/components/shared/footer/footer.component.scss
src/app/components/shared/related-articles/related-articles.component.scss
src/app/components/shared/sidebar/sidebar.component.scss
src/app/components/shared/top-bar/top-bar.component.scss
src/styles/variables.scss

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

fixing styles adding missing variables and removing default values

---

documentation.json
src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.ts
src/app/components/shared/label/label.component.html
src/app/components/shared/label/label.component.scss
src/app/components/shared/label/label.component.spec.ts
src/app/components/shared/label/label.component.ts
src/stories/label.stories.ts

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

[HCPS] - label component

---

documentation.json
src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.ts
src/app/components/shared/center-tab-bar/center-tab-bar.component.html
src/app/components/shared/center-tab-bar/center-tab-bar.component.scss
src/app/components/shared/center-tab-bar/center-tab-bar.component.spec.ts
src/app/components/shared/center-tab-bar/center-tab-bar.component.ts
src/stories/center-tab-bar.stories.ts

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

[HCPS] - center tab bar

---

src/app/components/shared/article-index/article-index.component.html
src/app/components/shared/article-index/article-index.component.scss
src/app/components/shared/sidebar/sidebar.component.scss

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

adding hover styles for sidebar and article-index

---

documentation.json
src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.ts
src/app/components/shared/carousel/carousel.component.html
src/app/components/shared/carousel/carousel.component.scss
src/app/components/shared/carousel/carousel.component.spec.ts
src/app/components/shared/carousel/carousel.component.ts
src/stories/carousel.stories.ts
src/styles/variables.scss

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

Hcps carousel

---

documentation.json
package-lock.json
src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.ts
src/app/components/shared/modal/modal.component.html
src/app/components/shared/modal/modal.component.scss
src/app/components/shared/modal/modal.component.spec.ts
src/app/components/shared/modal/modal.component.ts
src/stories/modal.stories.ts

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

Modal branch

---

src/app/components/shared/sidebar/sidebar.component.html
src/app/components/shared/sidebar/sidebar.component.ts

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

fixing sidebar behavior

---

src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.ts
src/app/components/shared/contact-us/contact-us.component.html
src/app/components/shared/contact-us/contact-us.component.scss

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

[HCPS] - contact us ui fixes

---

src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.scss
src/app/components/dashboard/dashboard.component.ts
src/app/services/data.service.spec.ts
src/app/services/data.service.ts

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

[HCPS] - creating service to read json contract

---

src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.ts
src/app/components/shared/card/card.component.ts
src/app/components/shared/card/news-container/news-container.component.html
src/app/components/shared/card/news-container/news-container.component.scss
src/app/components/shared/card/products-container/products-container.component.html
src/app/components/shared/card/products-container/products-container.component.scss
src/app/components/shared/card/topics-container/topics-container.component.html
src/app/components/shared/card/topics-container/topics-container.component.scss
src/app/components/shared/carousel/carousel.component.ts
src/app/services/data.service.ts

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

[HCPS] - topics from json

---

src/app/app.routes.ts
src/app/components/article/article.component.html
src/app/components/article/article.component.spec.ts
src/app/components/article/article.component.ts

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

[HCPS] - article route

---

src/app/components/article/article.component.html
src/app/components/article/article.component.scss
src/app/components/article/article.component.ts
src/app/components/dashboard/dashboard.component.scss
src/app/services/data.service.ts

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

[HCPS] - articles template

---

src/app/app.routes.ts
src/app/components/article/article.component.html
src/app/components/article/article.component.scss
src/app/components/article/article.component.ts
src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.scss
src/app/components/dashboard/dashboard.component.ts
src/app/components/page-not-found/page-not-found.component.html
src/app/components/page-not-found/page-not-found.component.scss
src/app/components/page-not-found/page-not-found.component.ts
src/app/components/shared/breadcrumb/breadcrumb.component.ts
src/app/components/shared/carousel/carousel.component.scss
src/app/components/shared/contact-us/contact-us.component.scss
src/app/components/shared/footer/footer.component.scss
src/app/components/shared/related-articles/related-articles.component.scss
src/app/components/shared/sidebar/sidebar.component.scss
src/app/services/auth.service.ts
src/app/services/data.service.ts
src/styles/variables.scss

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

NO-JIRA adding multiple changes for Demo and Services integration

---

src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.scss
src/app/components/dashboard/dashboard.component.ts
src/app/components/shared/carousel/carousel.component.scss
src/app/components/shared/carousel/carousel.component.ts
src/app/components/shared/related-articles/related-articles.component.scss
src/app/services/data.service.ts

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

[HCPS] - list components

---

src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.scss
src/app/components/dashboard/dashboard.component.ts
src/app/components/shared/card/news-container/news-container.component.html
src/app/components/shared/card/news-container/news-container.component.scss
src/app/components/shared/card/products-container/products-container.component.scss
src/app/components/shared/card/topics-container/topics-container.component.scss
src/app/components/shared/carousel/carousel.component.html
src/app/components/shared/carousel/carousel.component.scss
src/app/components/shared/carousel/carousel.component.ts
src/app/components/shared/related-articles/related-articles.component.html
src/app/components/shared/related-articles/related-articles.component.scss
src/app/components/shared/related-articles/related-articles.component.ts

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

[HCPS] - displaying data

---

src/app/components/dashboard/dashboard.component.scss
src/app/components/shared/related-articles/related-articles.component.scss

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

[HCPS] - dashboard ui fixes

---

src/app/components/article/article.component.html
src/app/components/article/article.component.scss
src/app/components/shared/contact-us/contact-us.component.scss

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

contact us

---

src/app/components/dashboard/dashboard.component.scss
src/app/components/shared/carousel/carousel.component.scss

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

[HCPS] - widht ui bug in dashboard

---

src/app/components/article/article.component.ts
src/app/components/dashboard/dashboard.component.ts
src/app/components/shared/header/header.component.ts
src/app/components/shared/search-bar/search-bar.component.ts

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

adding navigate service to searchbar and template

---

src/app/components/article/article.component.html
src/app/components/article/article.component.ts
src/app/components/shared/article-index/article-index.component.html
src/app/components/shared/article-index/article-index.component.ts
src/app/components/shared/article-section-title/article-section-title.component.html

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

adding behavior to article index

---

src/app/components/shared/header/header.component.ts

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

fixing route service in header

---

src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.ts
src/app/components/shared/header/header.component.html
src/app/components/shared/header/header.component.ts

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

adding pill support for search bar

---

src/app/components/article/article.component.html
src/app/components/article/article.component.ts

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

including pill support for article

---

src/app/components/article/article.component.html
src/app/components/article/article.component.ts
src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.ts
src/app/components/shared/card/news-container/news-container.component.scss
src/app/components/shared/header/header.component.html
src/app/components/shared/header/header.component.ts
src/app/components/shared/search-bar/search-bar.component.html
src/app/components/shared/search-bar/search-bar.component.ts
src/app/components/shared/sidebar/sidebar.component.ts
src/app/services/data.service.ts

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

No jira latest changes

---

src/app/components/dashboard/dashboard.component.html
src/app/components/shared/card/news-container/news-container.component.scss
src/app/components/shared/header/header.component.html
src/app/components/shared/header/header.component.ts

**Article**
List view:
Entry view:
**Page**
Entry view:
- List view
- Single log
- Field level
- Locale
- Roles 
- Add New Role

[HCPS] - responsive dashboard merge
